export const cardMocks = [
  {
    id: "1",
    title: "SOFA",
    image: "sofa.png",
    category: "Design",
  },
  {
    id: "2",
    title: "KeyBoard",
    image: "keyboard.png",
    category: "Branding",
  },
  {
    id: "3",
    title: "Work Media",
    image: "work-media.png",
    category: "Illustration",
  },
  {
    id: "4",
    title: "DDDone",
    image: "dddone.png",
    category: "Motion",
  },
  {
    id: "5",
    title: "Abstract",
    image: "abstract.png",
    category: "Design",
  },
  {
    id: "6",
    title: "HandP",
    image: "handp.png",
    category: "Branding",
  },
  {
    id: "7",
    title: "Architect",
    image: "architect.png",
    category: "Motion",
  },
  {
    id: "8",
    title: "Calc",
    image: "calc.png",
    category: "Design",
  },
  {
    id: "9",
    title: "Sport",
    image: "sport.png",
    category: "Branding",
  },
  {
    id: "10",
    title: "SOFA2",
    image: "sofa.png",
    category: "Design",
  },
  {
    id: "11",
    title: "KeyBoard2",
    image: "keyboard.png",
    category: "Branding",
  },
  {
    id: "12",
    title: "Work Media2",
    image: "work-media.png",
    category: "Illustration",
  },
  {
    id: "13",
    title: "DDDone2",
    image: "dddone.png",
    category: "Motion",
  },
  {
    id: "14",
    title: "Abstract2",
    image: "abstract.png",
    category: "Design",
  },
  {
    id: "15",
    title: "HandP2",
    image: "handp.png",
    category: "Branding",
  },
  {
    id: "16",
    title: "Architect2",
    image: "architect.png",
    category: "Motion",
  },
  {
    id: "17",
    title: "Calc2",
    image: "calc.png",
    category: "Design",
  },
  {
    id: "18",
    title: "Sport2",
    image: "sport.png",
    category: "Branding",
  },
];